version: '2'
services:
  debait-renderer:
    image: video-renderer:latest
    container_name: debait-renderer
    volumes:
      - ./files:/app/files
    environment:
      - REDIS_HOST=debait-redis
    networks:
      - debait-net
    depends_on:
      - debait-redis
  websocket:
    image: debait-websocket-server:latest
    container_name: websocket
    volumes:
      - ./files:/app/files
    ports:
      - 10000-10100:10000-10100/tcp
      - 10000-10100:10000-10100/udp
    networks:
      - debait-net
  debait-redis:
      image: redis:alpine
      container_name: debait-redis
      command: redis-server --port 6379
      networks:
        - debait-net
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
  debait-nginx:
    image: nginx:1.25.3-alpine
    container_name: debait-nginx
    networks:
      - debait-net
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl
      - ./public:/public
    depends_on:
      - websocket

networks:
  debait-net:
    driver: bridge