version: '2'
services:
  debait-db:
    image: mysql
    container_name: debait-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: junjong2024QAWSEDRF
      MYSQL_ROOT_HOST: '0.0.0.0'
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
    networks:
      - debait-net
  debait-renderer:
    image: video-renderer:latest
    container_name: debait-renderer
    volumes:
      - ./public/files:/app/files
    environment:
      RABBITMQ_HOST: debait-rabbitmq
      API_HOST: http://debait-api-server:8080
    networks:
      - debait-net
    depends_on:
      - debait-rabbitmq
      - websocket
  debait-api-server:
    image: debait-api-server:latest
    container_name: debait-api-server
    environment:
      SOCKET_SERVER_URL: http://websocket:3000
    depends_on:
      - debait-db
    networks:
      - debait-net
  websocket:
    image: debait-websocket-server:latest
    container_name: websocket
    volumes:
      - ./public/files:/app/files
    ports:
      - '3001:3000'
      - 10000-10100:10000-10100/tcp
      - 10000-10100:10000-10100/udp
    environment:
      RABBITMQ_HOST: debait-rabbitmq
      RECORD_FILE_LOCATION_PATH: ./files
      JWT_SECRET: 11111111sdfasfewdhtdfgdfaesg349dasdjasdijdsfdgddsadafsvfadsgsfaegfvdsafdsasdasdsadwefdefw
    networks:
      - debait-net
  debait-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: debait-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - debait-net
  debait-nginx:
    image: nginx:1.25.3-alpine
    container_name: debait-nginx
    networks:
      - debait-net
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl
      - ./public:/public
    depends_on:
      - websocket

networks:
  debait-net:
    driver: bridge